### ISSUE TITLE
Is there a specific reason you wrote the cloud-functions file in JS instead of TS?

### ISSUE THREAD

**Issue by Evertt** [babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template#21]
Title says it all. I'm a bit surprised about it and I'm wondering if you had tried using TS for it and ran into issues.

**Comment by babichjacob** [comment]
You're not expected to write *the source of* auxiliary Cloud Functions in the `/index.js` file. 

There is [a note in `src/server.ts`](https://github.com/babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template/blob/main/src/server.ts#L42-L43) that that is the place you should write the body of your Cloud Functions and import them in `/index.js` the same way `createSapperAndApolloServer` is. Your `/index.js` file will stay relatively small so the things you'll be doing there won't be very worthwhile to have TypeScript help with.

If `/index.ts` was written in TypeScript, there'd need to be an extra step in the build process to transpile it (which would require modifications to `tsconfig.json`'s `include` and it's likely other semi-unfixable IDE errors or warnings would still remain), the transpiled file would need to be `.gitignore`d, and maybe other things I can't foresee now.

For these reasons, writing `/index` as TypeScript instead of JavaScript has too few benefits and too many drawbacks.
