### ISSUE TITLE
Recommendation For WendiCSS - Perfect For Your Project, Remove Purge CSS & Post CSS 

### ISSUE THREAD

**Issue by ZetiMente** [babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template#28]
Github recommended your repo to me and it's a very similar stack and design to what we are doing. WendiCSS would be great for you as it was for us because it removed PurgeCSS and PostCSS making the CSS config less obtuse and increased performance. Instead of purgeCSS at the end, the goal of WendiCSS is to only give the CSS you need from Tailwind CSS.  I'm  not affiliated with WendiCSS in any way, but I think it would help your software by removing dependencies. It is a new project, so there is a risk of bugs but it is a very exciting project. Doing the migration was ok, some trial and error in configuration and there was a some CSS things that had to be changed. But the end result is much faster build times and more efficient use of tailwindCSS. 

This is just my suggestion. Bonus, you can also remove autoPrefixer. So that is 3 dependencies.

**Comment by babichjacob** [comment]
Hi, thank you for your interest in the project! I don't have the full bandwidth to reply to this in full, so here's a short excerpt summarizing my thoughts:

This project is "stale" now and won't be getting feature updates or breaking changes like that before its lifetime is over. I already, unfortunately, have difficulty maintaining it (seeing as the last commit is from December).

WindiCSS as a project interests me! I have some worries about how it handles Tailwind plugins that were written to use the PostCSS API since I use / wrote one of those and that needs more testing than I'm capable of doing right now. Additionally, the performance problem it was meant to solve seems to be attempted to be tackled by the Tailwind Labs team as of earlier today / this week: https://twitter.com/adamwathan/status/1366509825186795524

So yeah, things need to grow for the next few weeks / months before I look into this again. In short, this project won't change but my future projects (like the Svelte Adder for Tailwind CSS) *may* take advantage of WindiCSS as an optional alternative to Tailwind CSS.

**Comment by ZetiMente** [comment]
I liked your ideas here of creating a reactive performant complete web framework (stack) around Svelte. I thought this could become a framework. And I like your ideas of the add-svelte, similar to composer in Ruby in Rails. And then all your components add together to this project. Then have a shell script that could allow you to get default configurations that work and which add-svelte programs you want to use. That would be amazing tooling for the svelte eco-system. 

This stack is extremely powerful and robust but very annoying and difficult to configure. And with Firebase, you have a list of Firestore, Auth, Storage, Cloud Functions. 

I should have read your README more carefully. I thought maintain till SvelteKit, meant you were going to add SvelteKit into this project instead of Sapper. With the way everything is so component based, you could probably swap Routify and SvelteKit in and out as well. And if Tailwind Labs is adding the ideas from WendiCSS into TailwindCSS, then I will thank WendiCSS for its noble cause. Assuming of course, Tailwind Labs does a better job. 

And I see someone else had the same ideas in the closed issues. Anyways, appreciate your work. I'll look into trying svelte-add/graphql
